name: "Pipeline"

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "docs/**"

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure/terraform

    outputs:
      k8s_cluster_id: ${{ steps.apply_terraform.outputs.k8s_cluster_id }}
      container_registry: ${{ steps.apply_terraform.outputs.container_registry }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: "Apply Terraform"
        id: apply_terraform
        uses: ./.github/workflows/terraform
        with:
          scw-access-key: ${{ secrets.SCW_ACCESS_KEY }}
          scw-secret-key: ${{ secrets.SCW_SECRET_KEY }}
          aws-access-key-id: ${{ secrets.SCW_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SCW_SECRET_KEY }}
